title: Alex Wyett
email: alex.wyett@gmail.com
description: Just another developer blog
baseurl: ""
url: "http://localhost:2610"

relative_permalinks: false

github_username: alexwyett

defaults:
  -
    scope:
      path: ""      # empty string for all files
      type: posts   # limit to posts
    values:
      is_post: true # automatically set is_post=true for all posts

include: ["_pages"]

# Exclude files and folder
exclude:
  - node_modules
  - gulpfile.js
  - package.json
  - bower.json
  - bower_components
  - yarn.lock